/**
 * Placeholder Main.java file for replit.
 *       DO NOT EDIT THIS FILE!!
 * Any changes to this file will not be graded.
 */
public class Main {

  /**
   * Call textAnalysis.
   */
  public static void main(String[] args) {
    TextAnalysis.main(null);
  }
}
